### ISSUE TITLE
Problem with JSON decoder and sperimentschema.json

### ISSUE THREAD

**Issue by adamliter** [presleyp/Speriment#59]
I just tried setting up an experiment on a machine other than the one that I've been working on. Because of the problem mentioned in https://github.com/presleyp/Speriment/issues/7#issuecomment-202158967, I tried copy and pasting `sperimentschema.json` from your master branch (currently at https://github.com/presleyp/Speriment/commit/c8a1e764b2b81e1fb06c2219744ad82c392a25d5).

When I tried to run my experiment file, I then got this hard(-for-me-)-to-deciper Traceback call with a Value Error.

```sh
Traceback (most recent call last):
  File "VSH_Exp4_10.py", line 494, in <module>
    experiment.install('VSH_Exp4_OnlineExp')
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 79, in install
    self.to_file('./static/js/' + filename, varname)
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 68, in to_file
    self._validate_json(json_experiment)
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 57, in _validate_json
    schema = json.loads(contents)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 83 column 99 (char 2731)
```

However, using the [`sperimentschema.json`](https://github.com/presleyp/Speriment/blob/0.7.0/speriment/sperimentschema.json) file from the 0.7.0 release seems to fix this problem (at least things seem to work as I expect them to).

**Comment by presleyp** [comment]
Looks like it's expecting a comma on line 83 of your script that isn't there. What's on that line (and maybe the previous one)? If it's a problem with the updated schema that'll tell me where to look.

**Comment by adamliter** [comment]
I've since edited the script a little bit, but I have it under version control. So I think (but I'm not positive) that the version I was using when I tried this had the following on line 83:

```python
return ListOfStimuli
```

This was part of a function definition:

```python
        def MutateStimuli(ListOfStimuli, Type, GeneralType):
            """
            Takes a list of dictionaries (ListOfStimuli) and two strings (Type, GeneralType)
            Returns an updated list of dictionaries with three new key-value pairs (SOUND, TYPE, and GENERAL_TYPE)
            """
            # Update the dictionaries in the list of stimuli
            for dict in ListOfStimuli:
                dict.update({'TYPE': Type})
                dict.update({'GENERAL_TYPE': GeneralType})
                dict.update({'SOUND': '/static/Recordings/' + dict['STIMULUS'] + '.wav'})
            # Return the list of stimuli
            return ListOfStimuli
```

Are the line numbers from the traceback tied my experiment script, though? There's nothing in column 99 on that line.

There are a few things that extend out to column 99 in my script, but not many. The only thing roughly around this area in my script that extends out to column 99 is the doc string of the above function and some comments.

**Comment by presleyp** [comment]
Oh, sorry, it would be a line from the json file produced by your script.

**Comment by adamliter** [comment]
Ah, gotcha, sorry! Is that the `.js` file that is written to `/static/js`? Or is there another file that gets written in the process?

**Comment by adamliter** [comment]
I can reproduce this again with the old experiment script, but the `.js` file in `/static/js` doesn't get written because the script fails, so is there somewhere else that I should be looking for the line number?

In reproducing it, I've gotten a new, but similar error:

```
Traceback (most recent call last):
  File "VSH_Exp4_10.py", line 494, in <module>
    experiment.install('VSH_Exp4_OnlineExp')
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 79, in install
    self.to_file('./static/js/' + filename, varname)
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 68, in to_file
    self._validate_json(json_experiment)
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 57, in _validate_json
    schema = json.loads(contents)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 48 column 31 (char 1439)
```

I'll keep this buggy implementation floating around on my computer if you have any suggestions for helping me to help you debug it. :smile:

**Comment by presleyp** [comment]
You can call `my_experiment.toJSON()` to look at the JSON it's producing.

**Comment by adamliter** [comment]
Ah, right. Thanks! Sorry, I should have thought of that.

So something really odd seems to be going on. Here's a shell transcript with some comments that I've added to help you decipher things. Line 48 seems okay?

```
(test) Adams-MacBook-Pro:test $ python -i VSH_Exp4_10.py
Traceback (most recent call last):
  File "VSH_Exp4_10.py", line 494, in <module>
    experiment.install('VSH_Exp4_OnlineExp')
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 79, in install
    self.to_file('./static/js/' + filename, varname)
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 68, in to_file
    self._validate_json(json_experiment)
  File "/Users/adamliter/.virtualenvs/test/lib/python2.7/site-packages/speriment/components/experiment.py", line 57, in _validate_json
    schema = json.loads(contents)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 48 column 31 (char 1439)
>>> file = open("test.json", "w")
>>> file.write(experiment.to_JSON())
>>> file.close()
>>> quit()
(test) Adams-MacBook-Pro:test $ tail -n +40 test.json | head -n $((56-40+1))    # prints lines 40-55 of test.json
                                "SEGMENT2": "a",                                # line 40
                                "STOP": "no",                                   # line 41
                                "SEGMENT4": "u",                                # line 42
                                "VOICING": "no",                                # line 43
                                "GENERAL_TYPE": "Training",                     # line 44
                                "PLACE": "bilabial",                            # line 45
                                "TYPE": "TrainingItems"                         # line 46
                            }                                                   # line 47
                        },                                                      # line 48
                        {                                                       # line 49
                            "id": "139",                                        # line 50
                            "text": [                                           # line 51
                                "Silently mouth the following word: <br><br>",  # line 51
                                "dibu"                                          # line 52
                            ],                                                  # line 53
                            "resources": [                                      # line 54
                                {                                               # line 55
```

**Comment by presleyp** [comment]
Oh I was thinking about this all wrong. I guess it's turning the schema file into Python. But I checked the current schema file and it doesn't have that first missing comma. I'll just keep an eye on the schema file I guess. I do have a goal of improving test coverage.

**Comment by adamliter** [comment]
Hmm, okay, sounds good. For the moment, I'm still just using the old `sperinetschema.json` file from the 0.7.0 release, and everything is working fine. It's only the newest `sperimentschema.json` file that is giving me trouble.

**Comment by joanagomesrb** [comment]
How did you solve the problem about the line "return _default_decoder.decode(s)"?
